---
#  tasks:
#To check if Docker is already installed before proceeding with the installation,
- name: check docker installation and register the resualt
  command: docker --version
  register: docker_output
  changed_when: false
  ignore_errors: true

- name: fail if docker already installed
  fail:
    msg: "Docker is already installed"
  when: docker_output.rc == 0

# Step1: we need to install all the dependances 
- name: install dependencies
  apt:
    name: '{{ docker_dep }}'
    state: latest
    update_cache: yes
  tags: 
    - docker
    - docker-compose

- name: Create /etc/apt/keyrings directory with the correct permissions
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
      #command: sudo install -m 0755 -d /etc/apt/keyrings

# Step2: Download the gpg key
- name: GPG key
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
# get_url:
#   url: https://download.docker.com/linux/ubuntu/gpg
#   dest: /etc/apt/keyrings/docker.asc
#   mode: '0644'
# tags: docker
#
####i    #- name: chanage mode for the
    #command: sudo chmod a+r /etc/apt/keyrings/docker.asc

# Step3: Add Docker Repositories
#- name: repository docker
#  apt_repository:
#   repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
#    state: present
      # tags: docker
- name: update repo
  command: >
        sh -c 'echo
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc]
        https://download.docker.com/linux/ubuntu
        $(. /etc/os-release && echo $VERSION_CODENAME) stable" |
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&
        sudo apt-get update'
  changed_when: true




# Step4: Install docker-ce docker-ce-cli containerd.io packages
- name: install docker
  apt:
    name: '{{ docker_pkg }}'
    state: latest
    update_cache: yes
  tags: docker
  notify: dockerservice

# Step5: Add user to docker group
- name: adding users to group docker
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  loop: '{{ docker_users }}'
  tags: adding users

#To check if Docker Compose is already installed before proceeding with the installation,
- name: check docker installation; register the resualt
  command: "docker-compose --version"
  register: docker_compose_output
  changed_when: false
  tags: compose
  ignore_errors: true

- name: fail if docker compose already installed
  fail:
    msg: "Docker Compose is already installed"
  when: docker_compose_output.rc == 0
  tags: compose


# Step5: Install docker-compose
- name: Install docker-compose
  apt:
    name: docker-compose
    #dest: /usr/local/bin/docker-compose
    #mode: '755'
  tags: current
