---
#vars

docker_dep:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_pkg:
  - docker-ce={{ docker_version }}
  - docker-ce-cli={{ docker_version }}
  - containerd.io

docker_users:
  - alia
  - ansible

docker_version: "5:20.10.7~3-0~ubuntu-focal"
docker_compose_version: "1.29.2"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"