---
#vars

docker_dep:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_pkg:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_users:
  - user1
  - user2