---
#vars

docker_dep:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_pkg:
  - docker-ce={{ docker_version }}
  - docker-ce-cli={{ docker_version }}
  - containerd.io

docker_users:
  - ubuntu
    #- ansible

docker_version: "5:27.2.0-1~ubuntu.24.04~noble"
docker_compose_version: "2.29.2-1~ubuntu.24.04~noble"
#docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
docker_compose_url: "http://in.archive.ubuntu.com/ubuntu noble/universe amd64 Packages"
